version: '3.7'
services:
  web:
    container_name: web-container
    build: ./web
    ports:
      - '8080:80'
    volumes:
      - ./html:/var/www/html
    restart: always
    depends_on:
      - db
  db:
    container_name: db-container
    build: ./db
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'asdf1234'
    volumes:
      - db-storage:/var/lib/mysql
    restart: always
volumes:
  db-storage:
